### ISSUE TITLE
Avoid String.fromCharCode

### ISSUE THREAD

**Issue by TiTi** [TShadwell/Horrible.js#3]
Hi,

I had a similar idea last year.
I managed to get rid of String.fromCharCode or use of "constructor".

([]+[]+{})[!+[]+!+[]+!+[]+!+[]+!+[]]+([]+[]+{})[+!+[]]+([]+[]+[][[]])[+!+[]]+(![]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[])[+!+[]]+(!![]+[])[!+[]+!+[]]+([]+[]+{})[!+[]+!+[]+!+[]+!+[]+!+[]]+(!![]+[])[+[]]+([]+[]+{})[+!+[]]+(!![]+[])[+!+[]]       "constructor"

See the comments and examples at : https://github.com/TiTi/jswtf/blob/master/jswtf.js

Cheers from France!

**Comment by TShadwell** [comment]
Oh wow, thanks, I'll get reading through that, I see we've both read wtfjs!
Take a look at nice.js I just wrote:
https://github.com/TShadwell/Nice.js
It makes ASCII art.
Cheers returned from England!

**Comment by TShadwell** [comment]
How did you deal with the issue that you can't cover all letters by fiddling around with arrays?
I use the String.fromCharCode to produce letters I can't make otherwise.
I managed to get rid of constructor- it's radio button #3

**Comment by TiTi** [comment]
Nice.js looks awesome.
I have no idea how you did that but it looks awesome.
I'll check the code as soon as possible.

Yep that's the main problem : i can't produce all letters.
Hum I remember a website with yellow background color that does something similar and is able to encrypt all letters.
From what I remember, they're not using String.fromCharCode but I might be wrong.
Yeah I finally find it !! (was afraid i couldn't find it back)
http://discogscounter.getfreehosting.co.uk/js-noalnum.php

Also this thread looks cool : http://stackoverflow.com/questions/7202157/can-you-explain-why-10

**Comment by TShadwell** [comment]
Thanks for that, looks like there's going to be some new features coming up!

**Comment by TiTi** [comment]
Also check out : http://utf-8.jp/public/jsfuck.html

**Comment by TShadwell** [comment]
I'm planning on implementing a 'kitchensink' type thing that allows people to fiddle with all sorts of options including the very long non alphanum conversions, I'm procrastinating a lot though, implementing a heavy UI would make the code less reusable.
